/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentalglyph;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aura Lintang
 */
public class pinjam extends javax.swing.JFrame {

    public pinjam() {
        initComponents();
        selectData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Motor = new javax.swing.JComboBox<>();
        Nama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Alamat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Nopol = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Nostruk = new javax.swing.JTextField();
        Pinjam = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Kembali = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        Harga = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        btnPrint1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("GLYPHXI RENTAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        Motor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----- Pilih Motor -----", "Vario", "Beat", "Vega ZR", "Bebek", "SupraX" }));
        Motor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotorActionPerformed(evt);
            }
        });
        getContentPane().add(Motor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 170, 30));

        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        getContentPane().add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 170, 30));

        jLabel2.setText("Motor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel3.setText("Alamat");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        Alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlamatActionPerformed(evt);
            }
        });
        getContentPane().add(Alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 170, 30));

        jLabel4.setText("Tgl Pinjam");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        Nopol.setEditable(false);
        Nopol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NopolActionPerformed(evt);
            }
        });
        getContentPane().add(Nopol, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 170, 30));

        jLabel5.setText("No Struk");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        Nostruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NostrukActionPerformed(evt);
            }
        });
        getContentPane().add(Nostruk, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 170, 30));
        getContentPane().add(Pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 170, 30));

        jLabel6.setText("No Polisi");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel7.setText("Tgl Kembali");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));
        getContentPane().add(Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 170, 30));

        jLabel8.setText("Harga");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        Harga.setEditable(false);
        Harga.setText("Rp 20.000");
        Harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaActionPerformed(evt);
            }
        });
        getContentPane().add(Harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 170, 30));

        btnExit.setText("EXIT");
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 690, 30));

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 150, 30));

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 150, 30));

        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 150, 30));

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "Alamat", "Motor", "No Polisi", "No Struk", "Tgl Pinjam", "Tgl Kembali", "Total Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblData);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 690, 160));

        jLabel9.setText("Nama");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        btnPrint1.setText("PRINT");
        btnPrint1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrint1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 150, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void AlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlamatActionPerformed

    private void NopolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NopolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NopolActionPerformed

    private void NostrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NostrukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NostrukActionPerformed

    private void HargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HargaActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void MotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotorActionPerformed
        // TODO add your handling code here:
        if(Motor.getSelectedItem().equals("Vario")){
           Nopol.setText("N 1234 A");
       }
       else if(Motor.getSelectedItem().equals("Beat")){
           Nopol.setText("N 5678 B");
       }
       else if(Motor.getSelectedItem().equals("Vega ZR")){
           Nopol.setText("N 910 C");
       } 
       else if(Motor.getSelectedItem().equals("Bebek")){
           Nopol.setText("N 1112 D");
       }
       else if(Motor.getSelectedItem().equals("SupraX")){
           Nopol.setText("N 1314 E");
       }
    }//GEN-LAST:event_MotorActionPerformed

    private void btnPrint1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrint1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrint1ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyy-MM-dd");
        String pinjam = dateFormat.format(Pinjam.getDate());
        String kembali = dateFormat.format(Kembali.getDate());
            
            if(Nama.getText().equals("") || 
                    Alamat.getText().equals("") || 
                    Motor.getSelectedItem().equals("") ||
                    Nopol.getText().equals("") || 
                    Nostruk.getText().equals("") ||
                    Harga.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error",
                        JOptionPane.WARNING_MESSAGE);
            } else {
                String SQL = "INSERT INTO peminjaman(nama, alamat, motor, no_pol, tgl_pinjam, tgl_kembali, harga)"+
                        "VALUES('"+Nama.getText()+"','"+Alamat.getText()+"',"+Motor.getSelectedItem().toString()+"',"+Nopol.getText()+"',"+Nostruk.getText()+"',"+pinjam+"',"+kembali+"'," +Harga.getText()+"')";
                int status = KoneksiDB.execute(SQL);
                if(status == 1){
                    JOptionPane.showMessageDialog(this,"Data Berhasil Ditambahkan","SUKSES",
                            JOptionPane.INFORMATION_MESSAGE);
                    selectData();
                }else {
                    JOptionPane.showMessageDialog(this,"Data Gagal Ditambahkan","GAGAL",
                            JOptionPane.WARNING_MESSAGE);
                }
            }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int baris = tblData.getSelectedRow();
        if (baris != -1) {
            String NoStruk = tblData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM `peminjaman` WHERE no_struk='"+NoStruk+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal Dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String user1 = login.user;
        Nama.setText(user1);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pinjam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alamat;
    private javax.swing.JTextField Harga;
    private com.toedter.calendar.JDateChooser Kembali;
    private javax.swing.JComboBox<String> Motor;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Nopol;
    private javax.swing.JTextField Nostruk;
    private com.toedter.calendar.JDateChooser Pinjam;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPrint1;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"Nama","Alamat","Motor","NoPolisi","NoStruk","TanggalPinjam","TanggalKembali","Harga"};
                DefaultTableModel dtm = new DefaultTableModel(null, kolom);
                String SQL = "SELECT * FROM peminjaman";
                ResultSet rs = KoneksiDB.executeQuery(SQL);
                try{
                    while(rs.next()) {
                        String Nama = rs.getString(1);
                        String Alamat = rs.getString(2);
                        String Motor = rs.getString(3);
                        String NoPolisi = rs.getString(4);
                        String NoStruk = rs.getString(5);
                        String TanggalPinjam = rs.getString(6);
                        String TanggalKembali = rs.getString(7);
                        String Harga = rs.getString(8);
                        String data[] = {Nama,Alamat,Motor,NoPolisi,NoStruk,TanggalPinjam,TanggalKembali,Harga};
                        dtm.addRow(data);
                    }
                }    
                catch (SQLException ex) {
                    Logger.getLogger(pinjam.class.getName()).log(Level.SEVERE, null, ex);
                }
                tblData.setModel(dtm);
    }
}
